name: pytest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: |
            Pipfile.lock
      - name: install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev --system --deploy
      - name: pytest
        run: pytest
